name: nyx_voice_assistant
version: 0.1.0
publish_to: 'none'
description: Cross-platform Nyx voice assistant client.

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  http: ^1.2.2

flutter:
  uses-material-design: true
